# 服务器设置
server:
  context-path: "/manage"
  port: 8080



# 数据库配置
c3p0:
  jdbcUrl: "jdbc:mysql://localhost:3306/housekeep?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false"
  user: "root"
  password: "root"
  driverClass: "com.mysql.jdbc.Driver"
  minPoolSize: 2
  maxPoolSize: 10
  #最大空闲时间,60秒内未使用则连接被丢弃。若为0则永不丢弃。 Default:0
  maxIdleTime: 600
  #当连接池中的连接耗尽的时候c3p0一次同时获取的连接数. Default:3
  acquireIncrement: 3
  #DBC的标准,用以控制数据源内加载的PreparedStatements数量。
  #但由于预缓存的statements属于单个connection而不是整个连接池所以设置这个参数需要考虑到多方面的因数.
  #如果maxStatements与maxStatementsPerConnection均为0,则缓存被关闭。Default:0
  maxStatements: 5
  #指定连接池的初始化连接数  取值应在minPoolSize 与 maxPoolSize 之间.Default:3
  initialPoolSize: 3
  #每60秒检查所有连接池中的空闲连接.Default:0
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false




spring:
  # 邮箱配置
  mail:
    host: smtp.sina.com
    username: fuxiuyang100@sina.com
    password: 12345678900
    default-encoding: UTF-8
    form: fuxiuyang100@sina.com
    subject: "机密空间注册验证码"
    text: "感谢您注册机密空间。您的验证码为："









# 验证码配置
code:
  length: 4
  expireTime: 360

# 密码配置
password:
  # 密码的长度
  length: 32


# Token 配置
token:
  # 配置token失效时长为2个星期,14天。14*24*60*60
  expireTime: 1209600






